### ISSUE TITLE
Certain CI steps run several times without additional result

### ISSUE THREAD

**Issue by szepeviktor** [bitExpert/phpstan-magento#257]
```yaml
      - name: Check license
      - name: Run Codesniffer
      - name: Lint Neon files
      - name: Perform static code analysis
      - name: Execute unit tests
```

I think these should be ran only once

- Check license
- Run Codesniffer
- Lint Neon files

On what PHP version? With what Magento version?

From #256
